import React from 'react';
import { 
  TrendingUp, 
  Award, 
  CheckCircle2, 
  Calendar, 
  Download, 
  Sparkles, 
  FolderGit2, 
  HelpCircle, 
  Map, 
  ArrowRight
} from 'lucide-react';
import { ResponsiveContainer, LineChart, Line, XAxis, YAxis, Tooltip, CartesianGrid } from 'recharts';
import { useApp } from '../../context/AppContext';

export const ProgressView: React.FC = () => {
  const { 
    user, 
    currentRole, 
    analysisResult, 
    roadmapWeeks, 
    projectRecommendations, 
    completedQuestionIds, 
    setActiveTab, 
    showNotification 
  } = useApp();

  const totalTasks = roadmapWeeks.reduce((sum, w) => sum + w.tasks.length, 0);
  const completedTasks = roadmapWeeks.reduce((sum, w) => sum + w.tasks.filter(t => t.completed).length, 0);
  const completedProjects = projectRecommendations.filter(p => p.isCompleted).length;

  const historyData = [
    { date: 'Initial Scan', score: 52, note: 'Initial Resume Upload' },
    { date: 'Week 1', score: 60, note: 'Deep Learning Foundation' },
    { date: 'Week 2', score: 68, note: 'CNN & Computer Vision' },
    { date: 'Current', score: analysisResult.jobReadinessScore, note: 'Active Status' }
  ];

  const handleExportReport = () => {
    const reportText = `================================================
AI CAREER & SKILL GAP ANALYSIS REPORT
Candidate: ${user.name} (${user.email})
Target Job Role: ${currentRole.title}
Date: ${new Date().toLocaleDateString()}
================================================

EXECUTIVE SUMMARY:
- Job Readiness Score: ${analysisResult.jobReadinessScore}%
- Skill Match Score: ${analysisResult.skillMatchScore}%
- Strong Skills Count: ${analysisResult.strongSkillsCount}
- Missing Skills Gaps: ${analysisResult.missingSkillsCount}

TOP STRENGTHS:
${analysisResult.strengthsSummary.map(s => `- ${s}`).join('\n')}

PRIMARY CRITICAL GAPS TO ADDRESS:
${analysisResult.weaknessesSummary.map(w => `- ${w}`).join('\n')}

AI EVALUATION:
${analysisResult.aiExplanation}

ROADMAP PROGRESS:
- ${completedTasks} of ${totalTasks} weekly tasks completed
- ${completedProjects} portfolio projects completed
- ${completedQuestionIds.length} technical interview questions mastered

Generated by CareerGap AI Platform.
`;

    const blob = new Blob([reportText], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${user.name.replace(/\s+/g, '_')}_Career_Gap_Report.txt`;
    link.click();
    URL.revokeObjectURL(url);
    showNotification('Career Readiness Report downloaded successfully!');
  };

  return (
    <div className="p-4 sm:p-8 flex-1 flex flex-col gap-6 overflow-y-auto custom-scrollbar">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <h2 className="text-xl sm:text-2xl font-extrabold text-white tracking-tight">
              Career Progress & Readiness Tracking
            </h2>
            <span className="text-xs font-semibold px-2 py-0.5 rounded-full bg-indigo-500/10 text-indigo-400 border border-indigo-500/20">
              Score: {analysisResult.jobReadinessScore}%
            </span>
          </div>
          <p className="text-xs text-gray-400 mt-1">
            Track your score velocity and milestones over time as you complete roadmap items for <span className="text-indigo-400 font-semibold">{currentRole.title}</span>.
          </p>
        </div>

        <button
          onClick={handleExportReport}
          className="px-4 py-2.5 bg-indigo-600 hover:bg-indigo-500 text-white rounded-xl text-xs font-bold transition-all shadow-lg shadow-indigo-900/30 flex items-center gap-2 self-start sm:self-auto cursor-pointer"
        >
          <Download className="w-3.5 h-3.5" />
          <span>Export Career Report (TXT)</span>
        </button>
      </div>

      {/* Progress Chart */}
      <div className="bg-[#141414] border border-[#222] p-6 rounded-2xl shadow-sm">
        <div className="flex justify-between items-center mb-6">
          <div>
            <h4 className="text-sm font-bold text-white tracking-wide">Readiness Score Velocity</h4>
            <p className="text-[11px] text-gray-400">Score growth as milestones and projects are completed</p>
          </div>
          <div className="flex items-center gap-1.5 text-xs font-bold text-emerald-400 bg-emerald-500/10 border border-emerald-500/20 px-3 py-1 rounded-full">
            <TrendingUp className="w-3.5 h-3.5" />
            +20% Overall Growth
          </div>
        </div>

        <div className="h-64 w-full">
          <ResponsiveContainer width="100%" height="100%">
            <LineChart data={historyData} margin={{ top: 10, right: 30, left: 0, bottom: 0 }}>
              <CartesianGrid stroke="#222" strokeDasharray="3 3" />
              <XAxis dataKey="date" stroke="#666" tick={{ fill: '#888', fontSize: 11 }} />
              <YAxis domain={[40, 100]} stroke="#666" tick={{ fill: '#888', fontSize: 11 }} />
              <Tooltip 
                contentStyle={{ backgroundColor: '#181818', borderColor: '#333', borderRadius: '12px', fontSize: '11px', color: '#fff' }}
              />
              <Line 
                type="monotone" 
                dataKey="score" 
                name="Job Readiness Score" 
                stroke="#6366f1" 
                strokeWidth={3} 
                dot={{ fill: '#6366f1', r: 5 }} 
                activeDot={{ r: 8 }} 
              />
            </LineChart>
          </ResponsiveContainer>
        </div>
      </div>

      {/* 3 Milestone Achievements Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <div className="bg-[#141414] border border-[#222] p-5 rounded-2xl space-y-3">
          <div className="flex justify-between items-center">
            <div className="p-2.5 rounded-xl bg-indigo-500/10 text-indigo-400 border border-indigo-500/20">
              <Map className="w-5 h-5" />
            </div>
            <span className="text-xs font-bold text-indigo-400">
              {Math.round((completedTasks / Math.max(1, totalTasks)) * 100)}% Done
            </span>
          </div>
          <div>
            <h4 className="text-sm font-bold text-white">Roadmap Milestones</h4>
            <p className="text-xs text-gray-400 mt-1">
              {completedTasks} of {totalTasks} weekly tasks and hands-on exercises completed.
            </p>
          </div>
          <button
            onClick={() => setActiveTab('roadmap')}
            className="text-xs text-indigo-400 hover:text-indigo-300 font-semibold flex items-center gap-1 pt-1"
          >
            <span>Continue Curriculum</span>
            <ArrowRight className="w-3 h-3" />
          </button>
        </div>

        <div className="bg-[#141414] border border-[#222] p-5 rounded-2xl space-y-3">
          <div className="flex justify-between items-center">
            <div className="p-2.5 rounded-xl bg-purple-500/10 text-purple-400 border border-purple-500/20">
              <FolderGit2 className="w-5 h-5" />
            </div>
            <span className="text-xs font-bold text-purple-400">
              {completedProjects} Built
            </span>
          </div>
          <div>
            <h4 className="text-sm font-bold text-white">Portfolio Projects</h4>
            <p className="text-xs text-gray-400 mt-1">
              {completedProjects} gap-targeted projects verified in your portfolio.
            </p>
          </div>
          <button
            onClick={() => setActiveTab('projects')}
            className="text-xs text-purple-400 hover:text-purple-300 font-semibold flex items-center gap-1 pt-1"
          >
            <span>Explore Projects</span>
            <ArrowRight className="w-3 h-3" />
          </button>
        </div>

        <div className="bg-[#141414] border border-[#222] p-5 rounded-2xl space-y-3">
          <div className="flex justify-between items-center">
            <div className="p-2.5 rounded-xl bg-emerald-500/10 text-emerald-400 border border-emerald-500/20">
              <HelpCircle className="w-5 h-5" />
            </div>
            <span className="text-xs font-bold text-emerald-400">
              {completedQuestionIds.length} Mastered
            </span>
          </div>
          <div>
            <h4 className="text-sm font-bold text-white">Interview Questions</h4>
            <p className="text-xs text-gray-400 mt-1">
              {completedQuestionIds.length} technical drills practiced and mastered.
            </p>
          </div>
          <button
            onClick={() => setActiveTab('interview')}
            className="text-xs text-emerald-400 hover:text-emerald-300 font-semibold flex items-center gap-1 pt-1"
          >
            <span>Practice Drills</span>
            <ArrowRight className="w-3 h-3" />
          </button>
        </div>
      </div>
    </div>
  );
};
